export const getAllBeneficieryByAccount = [
    {
        "id": "f4297563-061c-4179-9f9d-063d0261dd23",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL960030010001324654654",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1324654654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T09:10:54.493",
        "companyName": null,
        "createdAt": "2025-05-13T09:10:54.493",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "872172a9-7402-494f-bda2-0fa796cda7ad",
        "status": 1,
        "bankAccountHolderEmail": "signupbusitest@yopmail.com",
        "bankAccountHolderName": "test desc bene",
        "bankAccountHolderNickname": "",
        "firstName": "isltest",
        "lastName": "busi",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "dz",
        "beneficiaryState": "",
        "beneficiaryCity": "test",
        "beneficiaryStreet": "ertetert",
        "beneficiaryHouseNumber": "56564",
        "beneficiaryZipCode": "123456",
        "bankFlag": null,
        "currencyISO": {
            "code": "AUD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/AUD.png",
            "currencyName": null
        },
        "currency": "AUD",
        "paymentReason": 999,
        "reasonDesc": "test desc",
        "bankCountry": "dz",
        "bankName": "SOCIETE GENERALE ALGERIE",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "DZ580002100001113000000570",
        "swiftCode": "SOGEDZALXXX",
        "accountNumber": "113000000570",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-06-05T11:42:23.04",
        "companyName": null,
        "createdAt": "2025-06-05T11:42:16.813",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": "ertetert 56564, test,  123456",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "23afa179-3fe7-42da-90b2-130565998baf",
        "status": 1,
        "bankAccountHolderEmail": "wabisi2070@botsoko.com",
        "bankAccountHolderName": "Us Holder Acc",
        "bankAccountHolderNickname": "",
        "firstName": "First",
        "lastName": "last",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "us",
        "beneficiaryState": "Alaska",
        "beneficiaryCity": "Aleutians West Census Area",
        "beneficiaryStreet": "test",
        "beneficiaryHouseNumber": "123456",
        "beneficiaryZipCode": "236",
        "bankFlag": null,
        "currencyISO": {
            "code": "USD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/USD.png",
            "currencyName": null
        },
        "currency": "USD",
        "paymentReason": 20,
        "reasonDesc": null,
        "bankCountry": "us",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "00012345864",
        "bankAccountType": 2,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "24dfc7ff-268a-4595-a10d-07bf3c4d4b56"
            },
            {
                "docType": 11,
                "fileId": "d0dde7c2-7c6b-4312-b184-447debe3b680"
            },
            {
                "docType": 11,
                "fileId": "2ad65017-8660-4ed9-9ade-3997cefdc3c7"
            },
            {
                "docType": 11,
                "fileId": "f5cfd56f-2ccd-432c-ae9e-bc8375b70809"
            },
            {
                "docType": 11,
                "fileId": "b0f5ff6b-d113-41d9-9aa2-caf42fdc0f7f"
            }
        ],
        "updatedAt": "2025-04-30T10:32:43.507",
        "companyName": null,
        "createdAt": "2025-04-30T10:32:35.92",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "132465789",
        "beneficiaryAddress": "test 123456, Aleutians West Census Area, Alaska 236",
        "routingCodeType": 6,
        "routingCodeValue": "132465789",
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "0ff43722-4a26-496b-82a5-19a3e1a99240",
        "status": 1,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "אקאאגיטאייעכיגכ",
        "beneficiaryIdNumber": "455555555",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/12.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "12",
        "bankBranch": "202",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-11T15:54:17.017",
        "companyName": null,
        "createdAt": "2025-02-20T15:09:37.29",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "54518c61-69f5-4a21-b28a-22398646998b",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/12.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Hapoalim B.M",
        "bankAddress": null,
        "bankNumber": "12",
        "bankBranch": "11",
        "iban": "IL150120110000000066666",
        "swiftCode": "POALILIT",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-02-11T11:34:10.54",
        "companyName": null,
        "createdAt": "2025-02-11T11:34:10.54",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "08176388-0af7-4905-a5a1-4788ec843e75",
        "status": 1,
        "bankAccountHolderEmail": "test@gmail.com",
        "bankAccountHolderName": "todas",
        "bankAccountHolderNickname": "",
        "firstName": "thjm",
        "lastName": "wyf",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "al",
        "beneficiaryState": "",
        "beneficiaryCity": "hsv",
        "beneficiaryStreet": "hcwygs",
        "beneficiaryHouseNumber": "415617",
        "beneficiaryZipCode": "4167",
        "bankFlag": null,
        "currencyISO": {
            "code": "RON",
            "sign": "RON",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/RON.png",
            "currencyName": null
        },
        "currency": "RON",
        "paymentReason": 999,
        "reasonDesc": "today",
        "bankCountry": "dz",
        "bankName": "SOCIETE GENERALE ALGERIE",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "DZ580002100001113000000570",
        "swiftCode": "SOGEDZALXXX",
        "accountNumber": "113000000570",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-06-05T13:23:37.167",
        "companyName": null,
        "createdAt": "2025-06-05T13:01:42.21",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "al",
        "aba": "",
        "beneficiaryAddress": "hcwygs 415617, hsv,  4167",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "059f317c-a698-4b6c-ba97-66c1a76cba1a",
        "status": 1,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "אקאאג",
        "beneficiaryIdNumber": "521545644",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/12.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "12",
        "bankBranch": "774",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-11T12:38:57.187",
        "companyName": null,
        "createdAt": "2025-03-20T06:52:00.927",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "fe25637b-e62a-4988-8b28-696601abaaed",
        "status": 1,
        "bankAccountHolderEmail": "aadil.cmarix@gmail.com",
        "bankAccountHolderName": "Mexico Acc",
        "bankAccountHolderNickname": "",
        "firstName": "jhon",
        "lastName": "doe",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "mx",
        "beneficiaryState": "Baja California Sur",
        "beneficiaryCity": "Cabo San Lucas",
        "beneficiaryStreet": "test",
        "beneficiaryHouseNumber": "123",
        "beneficiaryZipCode": "56",
        "bankFlag": null,
        "currencyISO": {
            "code": "MXN",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/MXN.png",
            "currencyName": null
        },
        "currency": "MXN",
        "paymentReason": 10,
        "reasonDesc": null,
        "bankCountry": "mx",
        "bankName": "BBVA MEXICO S.A.",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "BCMRMXMMPYM",
        "accountNumber": "113000000570",
        "bankAccountType": 2,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "aa7869de-c1d2-4342-b717-59d15d663b11"
            },
            {
                "docType": 2,
                "fileId": "f015b6bc-2390-4c86-b494-9db71782fb9a"
            }
        ],
        "updatedAt": "2025-05-02T12:41:03.393",
        "companyName": null,
        "createdAt": "2025-04-30T10:34:16.587",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "test 123, Cabo San Lucas, Baja California Sur 56",
        "routingCodeType": 4,
        "routingCodeValue": "101546446545645645",
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "1f7f51f0-8fd2-43b0-8ed1-6a8eea16cd96",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/13.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Union Bank of Israel Ltd",
        "bankAddress": null,
        "bankNumber": "13",
        "bankBranch": "64",
        "iban": "IL080130640000000123456",
        "swiftCode": "UNBKILIT",
        "accountNumber": "123456",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T10:01:41.063",
        "companyName": null,
        "createdAt": "2025-05-13T10:01:41.063",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "60cef256-c2eb-41f7-883d-6e09504a16f4",
        "status": 1,
        "bankAccountHolderEmail": "gicopem869@gam1fy.com",
        "bankAccountHolderName": "test holder name bene",
        "bankAccountHolderNickname": "",
        "firstName": "rerow",
        "lastName": "test",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "al",
        "beneficiaryState": "",
        "beneficiaryCity": "fdsf",
        "beneficiaryStreet": "Derech Sheshet HaYam",
        "beneficiaryHouseNumber": "6536543654",
        "beneficiaryZipCode": "456444",
        "bankFlag": null,
        "currencyISO": {
            "code": "GBP",
            "sign": "£",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/GBP.png",
            "currencyName": null
        },
        "currency": "GBP",
        "paymentReason": 999,
        "reasonDesc": "test desc",
        "bankCountry": "dz",
        "bankName": "SOCIETE GENERALE ALGERIE",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "DZ580002100001113000000570",
        "swiftCode": "SOGEDZALXXX",
        "accountNumber": "113000000570",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-06-05T13:07:37.707",
        "companyName": null,
        "createdAt": "2025-06-05T13:07:31.8",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": "Derech Sheshet HaYam 6536543654, fdsf,  456444",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "81abbf9e-cf2b-4132-9826-7758073243ff",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/12.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Hapoalim B.M",
        "bankAddress": null,
        "bankNumber": "12",
        "bankBranch": "11",
        "iban": "IL150120110000000066666",
        "swiftCode": "POALILIT",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-02-11T09:47:56.8",
        "companyName": null,
        "createdAt": "2025-02-11T09:47:56.8",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "78cce104-e839-4088-970d-79f7ef23c15c",
        "status": 1,
        "bankAccountHolderEmail": "gjo@yopmail.com",
        "bankAccountHolderName": "gdz",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "גסכ",
        "beneficiaryIdNumber": "568899900",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": null,
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "Bank Leumi Le-Israel B.M",
        "bankAddress": null,
        "bankNumber": "‏10 - בנק לאומי לישראל בע\"מ",
        "bankBranch": "‏772 - בועיינה נוג'ידאת",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "6575687575",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-06-11T10:48:29.533",
        "companyName": null,
        "createdAt": "2025-06-11T10:48:27.273",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "77ed17ab-0151-47cd-abc5-8c9fd52d6672",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL450030010000000000001",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-17T16:03:01.49",
        "companyName": null,
        "createdAt": "2025-04-17T16:03:01.49",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "d2234239-365c-4fcc-a4a8-91bea555d43f",
        "status": 1,
        "bankAccountHolderEmail": "fdsffdsf@gmail.com",
        "bankAccountHolderName": "Business Name",
        "bankAccountHolderNickname": "test",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "az",
        "beneficiaryState": "",
        "beneficiaryCity": "Bashkia Poliçan",
        "beneficiaryStreet": "rfgg",
        "beneficiaryHouseNumber": "545645",
        "beneficiaryZipCode": "345435",
        "bankFlag": null,
        "currencyISO": {
            "code": "GBP",
            "sign": "£",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/GBP.png",
            "currencyName": null
        },
        "currency": "GBP",
        "paymentReason": 10,
        "reasonDesc": null,
        "bankCountry": "bz",
        "bankName": "BELIZE BANK LIMITED",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "BBLZBZBZXXX",
        "accountNumber": "001234567890",
        "bankAccountType": 2,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 2,
                "fileId": "3928333d-7dca-45bd-8af0-fe840eec858d"
            },
            {
                "docType": 1,
                "fileId": "a81238e5-cb9d-4e13-b57c-74b698c58d2f"
            }
        ],
        "updatedAt": "2025-05-05T10:34:04.683",
        "companyName": null,
        "createdAt": "2025-05-02T12:53:00.323",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "rfgg 545645, Bashkia Poliçan,  345435",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "bb11702f-e2a1-4911-bada-9d71b571315a",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/4.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Yahav for Government Employees Ltd",
        "bankAddress": null,
        "bankNumber": "4",
        "bankBranch": "130",
        "iban": "IL790041302356789643564",
        "swiftCode": "BYAHILI1",
        "accountNumber": "2356789643564",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T09:56:14.687",
        "companyName": null,
        "createdAt": "2025-05-13T09:56:14.687",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "45efec50-b641-4641-98dc-9dfed4b1ce02",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL450030010000000000001",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-17T16:01:54.917",
        "companyName": null,
        "createdAt": "2025-04-17T16:01:54.917",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "c96d7997-53d6-4ed6-bd46-ab2d518d217c",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL960030010001324654654",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1324654654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T09:10:57.387",
        "companyName": null,
        "createdAt": "2025-05-13T09:10:57.387",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "7c38fd88-31b2-4095-8eb0-add9a2cd22e9",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/4.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Yahav for Government Employees Ltd",
        "bankAddress": null,
        "bankNumber": "4",
        "bankBranch": "131",
        "iban": "IL730041310001234565567",
        "swiftCode": "BYAHILI1",
        "accountNumber": "1234565567",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T10:02:45.227",
        "companyName": null,
        "createdAt": "2025-05-13T10:02:45.227",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "780793fc-d323-4d93-83d2-af78cc32956c",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL250030010000000123454",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "123454",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-12T08:30:43.853",
        "companyName": null,
        "createdAt": "2025-05-12T08:30:43.853",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "180d7fee-b434-4e15-9f38-b0dc881d92aa",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL960030010001324654654",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1324654654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T09:08:12.577",
        "companyName": null,
        "createdAt": "2025-05-13T09:08:12.577",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "d1d77b56-f7fd-4c87-b54e-be7fd9521b02",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL450030010000000000001",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-25T13:51:31.03",
        "companyName": null,
        "createdAt": "2025-04-25T13:51:31.03",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "053e6e9c-af43-4d9f-9546-c04f8e0cb0ea",
        "status": 1,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "hgfdhf hgfhgfdhf",
        "bankAccountHolderNickname": "",
        "firstName": "hgfdhf",
        "lastName": "hgfhgfdhf",
        "bankAccountHolderHebrewName": "חיכחעי חיעכחעיחי",
        "beneficiaryIdNumber": "521545641",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": null,
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "116",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-03-07T11:07:26.003",
        "companyName": null,
        "createdAt": "2025-03-07T11:07:26.003",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": true
    },
    {
        "id": "effd7991-28ea-4703-b6a5-cd1cf2003e57",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "900",
        "iban": "IL140039000000000123456",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "123456",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T10:09:17.867",
        "companyName": null,
        "createdAt": "2025-05-13T10:09:17.867",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "6046c93d-79b8-43c6-a48b-cdbed2793bc2",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/12.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Hapoalim B.M",
        "bankAddress": null,
        "bankNumber": "12",
        "bankBranch": "11",
        "iban": "IL150120110000000066666",
        "swiftCode": "POALILIT",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-02-20T15:04:42.047",
        "companyName": null,
        "createdAt": "2025-02-20T15:04:42.047",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "9f2368d2-e071-44db-8d94-cf8d9c64dda6",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/13.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Union Bank of Israel Ltd",
        "bankAddress": null,
        "bankNumber": "13",
        "bankBranch": "64",
        "iban": "IL080130640000000123456",
        "swiftCode": "UNBKILIT",
        "accountNumber": "123456",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-05-13T10:01:11.857",
        "companyName": null,
        "createdAt": "2025-05-13T10:01:11.857",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "bbcec6c6-0718-4e00-a4c6-d041a56f1d1b",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "900",
        "iban": "IL140039000000000123456",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "123456",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-22T09:05:37.58",
        "companyName": null,
        "createdAt": "2025-04-22T09:05:37.58",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "0a8e9894-7de6-485b-beda-d41bfb2c6bb5",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/11.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Israel Discount Bank Ltd",
        "bankAddress": null,
        "bankNumber": "11",
        "bankBranch": "12",
        "iban": "IL230110120000000066666",
        "swiftCode": "IDBLILIT",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-02-20T15:08:01.197",
        "companyName": null,
        "createdAt": "2025-02-20T15:08:01.197",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "509ab2da-0866-4732-b794-d7f2ae95a827",
        "status": 2,
        "bankAccountHolderEmail": "sandy@cambell.com",
        "bankAccountHolderName": "Sandy Cambell",
        "bankAccountHolderNickname": "Sandy ",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "al",
        "beneficiaryState": "",
        "beneficiaryCity": "City",
        "beneficiaryStreet": "Prahlad Park",
        "beneficiaryHouseNumber": "213",
        "beneficiaryZipCode": "38241",
        "bankFlag": null,
        "currencyISO": {
            "code": "USD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/USD.png",
            "currencyName": null
        },
        "currency": "USD",
        "paymentReason": 11,
        "reasonDesc": null,
        "bankCountry": "al",
        "bankName": "Credins Bank",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "AL47212110090000000235698741",
        "swiftCode": "CDISALTRXXX",
        "accountNumber": "90000000235698741",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "08afb6c1-2eca-4462-886e-1aefb48484e5"
            }
        ],
        "updatedAt": "2025-05-15T08:56:34.247",
        "companyName": null,
        "createdAt": "2025-05-15T08:56:21.377",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "Prahlad Park 213, City,  38241",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "a9adf685-0732-47d6-8361-f3bbdb3fca77",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL450030010000000000001",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-21T12:10:41.9",
        "companyName": null,
        "createdAt": "2025-04-21T12:10:41.9",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "951f2590-5b1d-4c22-9fdb-fd88719919f8",
        "status": 2,
        "bankAccountHolderEmail": "bebiyij325@cironex.com",
        "bankAccountHolderName": "Goha",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "52154564",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "Petah Tikva",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "65256541",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "900",
        "iban": "IL140039000000000123456",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "123456",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-22T09:05:25.223",
        "companyName": null,
        "createdAt": "2025-04-22T09:05:25.223",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "Petah Tikva,  65256541",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    }
]