export const monthlyExposureObject = {
  "pair": "EUR/USD",
  "sign": "$",
  "toCurrency": "USD",
  "selectedExposure": "Selling",
  "monthlyAmount": 100000,
  "monthlyPeriod": "12",
  "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/USD.png",
  "code": "USD",
  "baseCurrencyFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/EUR.png",
  "baseCurrency": "EUR",
  "baseCurrencySign": "€"
}

export const cashflowExposureData = [
  {
    "month": "Apr",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 30,
    "midDay": 15,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Apr",
    "monthNumber": 3,
    "cashflowDate": 15,
    "Month": "15/04/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "May",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "May",
    "monthNumber": 4,
    "cashflowDate": 15,
    "Month": "15/05/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Jun",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 30,
    "midDay": 15,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Jun",
    "monthNumber": 5,
    "cashflowDate": 15,
    "Month": "15/06/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Jul",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Jul",
    "monthNumber": 6,
    "cashflowDate": 15,
    "Month": "15/07/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Aug",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Aug",
    "monthNumber": 7,
    "cashflowDate": 15,
    "Month": "15/08/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Sep",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 30,
    "midDay": 15,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Sep",
    "monthNumber": 8,
    "cashflowDate": 15,
    "Month": "15/09/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Oct",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Oct",
    "monthNumber": 9,
    "cashflowDate": 15,
    "Month": "15/10/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Nov",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 30,
    "midDay": 15,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Nov",
    "monthNumber": 10,
    "cashflowDate": 15,
    "Month": "15/11/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Dec",
    "year": 2025,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Dec",
    "monthNumber": 11,
    "cashflowDate": 15,
    "Month": "15/12/2025",
    "dayOfExpity": "15"
  },
  {
    "month": "Jan",
    "year": 2026,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Jan",
    "monthNumber": 0,
    "cashflowDate": 15,
    "Month": "15/01/2026",
    "dayOfExpity": "15"
  },
  {
    "month": "Feb",
    "year": 2026,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 28,
    "midDay": 14,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Feb",
    "monthNumber": 1,
    "cashflowDate": 15,
    "Month": "15/02/2026",
    "dayOfExpity": "15"
  },
  {
    "month": "Mar",
    "year": 2026,
    "buying": "0",
    "selling": "100,000",
    "totalNetValue": 100000,
    "lastDay": 31,
    "midDay": 16,
    "openEditForBuying": false,
    "openEditForSelling": false,
    "errMsgForbuyingFlag": false,
    "errMsgForsellingFlag": false,
    "postPoneFlag": false,
    "postPoneInactiveFlag": true,
    "postPoneMonth": "Mar",
    "monthNumber": 2,
    "cashflowDate": 15,
    "Month": "15/03/2026",
    "dayOfExpity": "15"
  }
];