export const hedgeData = {
  "totalHedgeAmount": 161.10,
  "hedgeCurrency": {
    "code": "CHF",
    "sign": "CHF",
    "flag": null,
    "currencyName": null
  },
  "totalHedgePercent": 33.5625,
  "avgHedgeRate": 4.3747526315789473684210526316,
  "liabilityRate": 4.3747526315789473684210526316,
  "requiredCollateral": 67.637,
  "price": 0.0,
  "collateralAndPriceCur": {
    "code": "ILS",
    "sign": "₪",
    "flag": null,
    "currencyName": null
  },
  "direction": 2,
  "currencyPair": "CHF/ILS",
  "hedgingType": 1,
  "monthlyHedge": [
    {
      "status": {
        "type": 3,
        "descriprion": "Don't need to create hedge for zero reccomended hedge"
      },
      "maxHedgeAmount": 5.00,
      "recomendedHedgeAmount": 0.00,
      "hedge": null,
      "totalExposure": 5.00,
      "alreadyHedge": 0.0,
      "date": "15/06/2025",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 10.50,
      "hedge": {
        "strategyId": 132575,
        "hedgeRate": 4.3121,
        "expiryDate": "17/11/2025",
        "price": 0.0,
        "collateral": 4.408,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3121,
        "protectAmount": 10.50
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "17/11/2025",
      "hedgeError": true
    },
    {
      "status": {
        "type": 5,
        "descriprion": "Already purchased the entire protection deal for the month"
      },
      "maxHedgeAmount": 0.0,
      "recomendedHedgeAmount": 0.0,
      "hedge": null,
      "totalExposure": 0.0,
      "alreadyHedge": 0.0,
      "date": "15/07/2025",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 50.00,
      "recomendedHedgeAmount": 17.10,
      "hedge": {
        "strategyId": 132567,
        "hedgeRate": 4.2749,
        "expiryDate": "15/08/2025",
        "price": 0.0,
        "collateral": 7.179,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.2749,
        "protectAmount": 17.10
      },
      "totalExposure": 50.00,
      "alreadyHedge": 0.0,
      "date": "15/08/2025",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 14.25,
      "hedge": {
        "strategyId": 132573,
        "hedgeRate": 4.2872,
        "expiryDate": "15/09/2025",
        "price": 0.0,
        "collateral": 5.983,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.2872,
        "protectAmount": 14.25
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/09/2025",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 14.25,
      "hedge": {
        "strategyId": 132566,
        "hedgeRate": 4.2996,
        "expiryDate": "15/10/2025",
        "price": 0.0,
        "collateral": 5.983,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.2996,
        "protectAmount": 14.25
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/10/2025",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 6.75,
      "hedge": {
        "strategyId": 132570,
        "hedgeRate": 4.3491,
        "expiryDate": "16/02/2026",
        "price": 0.0,
        "collateral": 2.834,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3491,
        "protectAmount": 6.75
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "16/02/2026",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 10.50,
      "hedge": {
        "strategyId": 132577,
        "hedgeRate": 4.3373,
        "expiryDate": "15/01/2026",
        "price": 0.0,
        "collateral": 4.408,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3373,
        "protectAmount": 10.50
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/01/2026",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 6.75,
      "hedge": {
        "strategyId": 132564,
        "hedgeRate": 4.3609,
        "expiryDate": "16/03/2026",
        "price": 0.0,
        "collateral": 2.834,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3609,
        "protectAmount": 6.75
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "16/03/2026",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 6.75,
      "hedge": {
        "strategyId": 132569,
        "hedgeRate": 4.3728,
        "expiryDate": "15/04/2026",
        "price": 0.0,
        "collateral": 2.834,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3728,
        "protectAmount": 6.75
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/04/2026",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 6.75,
      "hedge": {
        "strategyId": 132565,
        "hedgeRate": 4.3728,
        "expiryDate": "15/05/2026",
        "price": 0.0,
        "collateral": 2.834,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3728,
        "protectAmount": 6.75
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/05/2026",
      "hedgeError": false
    },
    {
      "status": {
        "type": 1,
        "descriprion": "Created"
      },
      "maxHedgeAmount": 25.00,
      "recomendedHedgeAmount": 6.75,
      "hedge": {
        "strategyId": 132571,
        "hedgeRate": 4.3728,
        "expiryDate": "15/06/2026",
        "price": 0.0,
        "collateral": 2.834,
        "productName": "LOCK & UP",
        "productType": 1,
        "notionalCurrency": "CHF",
        "notionalCurrencySign": "CHF",
        "secondCurrency": "ILS",
        "secondCurrencySign": "₪",
        "collateralCurrency": "ILS",
        "liabilityRate": 4.3728,
        "protectAmount": 6.75
      },
      "totalExposure": 25.00,
      "alreadyHedge": 0.0,
      "date": "15/06/2026",
      "hedgeError": false
    },
  ]
};

export const hedgeAllRows = [
  {
      "expiryDate": "17/11/2025",
      "hedgeRate": 4.4568,
      "protectAmount": 8,
      "recommendedHedgeAmount": 8,
      "maxHedge_amount": 25,
      "collateral": 3.475,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 8,
      "hedge": {
          "strategyId": 132866,
          "hedgeRate": 4.4568,
          "expiryDate": "17/11/2025",
          "price": 0,
          "collateral": 3.475,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4568,
          "protectAmount": 8
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "17/11/2025"
  },
  {
      "expiryDate": "15/08/2025",
      "hedgeRate": 4.4202,
      "protectAmount": 14.1,
      "recommendedHedgeAmount": 14.1,
      "maxHedge_amount": 50,
      "collateral": 6.125,
      "totalExposureAmount": 50,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 50,
      "recomendedHedgeAmount": 14.1,
      "hedge": {
          "strategyId": 132867,
          "hedgeRate": 4.4202,
          "expiryDate": "15/08/2025",
          "price": 0,
          "collateral": 6.125,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4202,
          "protectAmount": 14.1
      },
      "totalExposure": 50,
      "alreadyHedge": 0,
      "date": "15/08/2025"
  },
  {
      "expiryDate": "15/09/2025",
      "hedgeRate": 4.4324,
      "protectAmount": 11.75,
      "recommendedHedgeAmount": 11.75,
      "maxHedge_amount": 25,
      "collateral": 5.104,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 11.75,
      "hedge": {
          "strategyId": 132869,
          "hedgeRate": 4.4324,
          "expiryDate": "15/09/2025",
          "price": 0,
          "collateral": 5.104,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4324,
          "protectAmount": 11.75
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/09/2025"
  },
  {
      "expiryDate": "15/10/2025",
      "hedgeRate": 4.4446,
      "protectAmount": 11.75,
      "recommendedHedgeAmount": 11.75,
      "maxHedge_amount": 25,
      "collateral": 5.104,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 11.75,
      "hedge": {
          "strategyId": 132854,
          "hedgeRate": 4.4446,
          "expiryDate": "15/10/2025",
          "price": 0,
          "collateral": 5.104,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4446,
          "protectAmount": 11.75
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/10/2025"
  },
  {
      "expiryDate": "16/02/2026",
      "hedgeRate": 4.4926,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132858,
          "hedgeRate": 4.4926,
          "expiryDate": "16/02/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4926,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "16/02/2026"
  },
  {
      "expiryDate": "15/01/2026",
      "hedgeRate": 4.4813,
      "protectAmount": 8,
      "recommendedHedgeAmount": 8,
      "maxHedge_amount": 25,
      "collateral": 3.475,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 8,
      "hedge": {
          "strategyId": 132856,
          "hedgeRate": 4.4813,
          "expiryDate": "15/01/2026",
          "price": 0,
          "collateral": 3.475,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.4813,
          "protectAmount": 8
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/01/2026"
  },
  {
      "expiryDate": "16/03/2026",
      "hedgeRate": 4.5039,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132868,
          "hedgeRate": 4.5039,
          "expiryDate": "16/03/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5039,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "16/03/2026"
  },
  {
      "expiryDate": "15/04/2026",
      "hedgeRate": 4.5152,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132862,
          "hedgeRate": 4.5152,
          "expiryDate": "15/04/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5152,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/04/2026"
  },
  {
      "expiryDate": "15/05/2026",
      "hedgeRate": 4.5152,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132853,
          "hedgeRate": 4.5152,
          "expiryDate": "15/05/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5152,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/05/2026"
  },
  {
      "expiryDate": "15/06/2026",
      "hedgeRate": 4.5152,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132871,
          "hedgeRate": 4.5152,
          "expiryDate": "15/06/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5152,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/06/2026"
  },
  {
      "expiryDate": "15/07/2026",
      "hedgeRate": 4.5152,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132855,
          "hedgeRate": 4.5152,
          "expiryDate": "15/07/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5152,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/07/2026"
  },
  {
      "expiryDate": "17/08/2026",
      "hedgeRate": 4.5152,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132857,
          "hedgeRate": 4.5152,
          "expiryDate": "17/08/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5152,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "17/08/2026"
  },
  {
      "expiryDate": "15/09/2026",
      "hedgeRate": 4.5156,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132860,
          "hedgeRate": 4.5156,
          "expiryDate": "15/09/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5156,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/09/2026"
  },
  {
      "expiryDate": "15/10/2026",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132859,
          "hedgeRate": 4.5833,
          "expiryDate": "15/10/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/10/2026"
  },
  {
      "expiryDate": "16/11/2026",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132861,
          "hedgeRate": 4.5833,
          "expiryDate": "16/11/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "16/11/2026"
  },
  {
      "expiryDate": "15/12/2026",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132863,
          "hedgeRate": 4.5833,
          "expiryDate": "15/12/2026",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/12/2026"
  },
  {
      "expiryDate": "15/01/2027",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132864,
          "hedgeRate": 4.5833,
          "expiryDate": "15/01/2027",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/01/2027"
  },
  {
      "expiryDate": "15/02/2027",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132865,
          "hedgeRate": 4.5833,
          "expiryDate": "15/02/2027",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/02/2027"
  },
  {
      "expiryDate": "15/03/2027",
      "hedgeRate": 4.5833,
      "protectAmount": 4.25,
      "recommendedHedgeAmount": 4.25,
      "maxHedge_amount": 25,
      "collateral": 1.846,
      "totalExposureAmount": 25,
      "openEditForSelling": false,
      "status": {
          "type": 1,
          "descriprion": "Created"
      },
      "maxHedgeAmount": 25,
      "recomendedHedgeAmount": 4.25,
      "hedge": {
          "strategyId": 132870,
          "hedgeRate": 4.5833,
          "expiryDate": "15/03/2027",
          "price": 0,
          "collateral": 1.846,
          "productName": "LOCK & UP",
          "productType": 1,
          "notionalCurrency": "CHF",
          "notionalCurrencySign": "CHF",
          "secondCurrency": "ILS",
          "secondCurrencySign": "₪",
          "collateralCurrency": "ILS",
          "liabilityRate": 4.5833,
          "protectAmount": 4.25
      },
      "totalExposure": 25,
      "alreadyHedge": 0,
      "date": "15/03/2027"
  }
]
