export const allbeneficiaryData = 
[
    {
        "id": "bb71d46f-7896-4ef8-8b64-01241df11d66",
        "status": 1,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "כגדכג",
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/31.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "31",
        "bankBranch": "30",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "105634654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-28T09:24:43.77",
        "companyName": null,
        "createdAt": "2025-03-25T14:16:39.033",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "c56357ae-aba3-483f-9635-01f56479ce4e",
        "status": 1,
        "bankAccountHolderEmail": "test@gmail.com",
        "bankAccountHolderName": "gsjd",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "יגת",
        "beneficiaryIdNumber": "838377732",
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": null,
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 25,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "",
        "bankAddress": null,
        "bankNumber": "‏11 - בנק דיסקונט לישראל בע\"מ",
        "bankBranch": "‏2 - עפולה",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "627383",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-01T17:16:34.38",
        "companyName": null,
        "createdAt": "2025-04-01T17:16:32.497",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "fedeba0e-1360-4961-976c-034d307aa247",
        "status": 2,
        "bankAccountHolderEmail": "t@gmail.com",
        "bankAccountHolderName": "ssss",
        "bankAccountHolderNickname": "test",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "cn",
        "beneficiaryState": "Anhui",
        "beneficiaryCity": "Bozhou",
        "beneficiaryStreet": "qwe",
        "beneficiaryHouseNumber": "23232",
        "beneficiaryZipCode": "123456",
        "bankFlag": null,
        "currencyISO": {
            "code": "EUR",
            "sign": "€",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/EUR.png",
            "currencyName": null
        },
        "currency": "EUR",
        "paymentReason": 11,
        "reasonDesc": null,
        "bankCountry": "ca",
        "bankName": "ROYAL BANK OF CANADA",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "ROYCCAT2XXX",
        "accountNumber": "355345634654",
        "bankAccountType": 2,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "38e25b33-77a5-4882-ab43-2422f59f4aed"
            },
            {
                "docType": 11,
                "fileId": "6af29718-5be6-4f2f-8425-bad1d974c751"
            },
            {
                "docType": 11,
                "fileId": "594a8fd4-a394-4e6c-ad4f-0b4e2d019d05"
            },
            {
                "docType": 11,
                "fileId": "804ee896-e8e6-4138-8190-0553c820ac65"
            }
        ],
        "updatedAt": "2025-05-08T09:01:58.48",
        "companyName": null,
        "createdAt": "2025-05-08T09:01:58.48",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "qwe 23232, Bozhou, Anhui 123456",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "b11ca663-48b3-4526-86b2-04a0460f3259",
        "status": 1,
        "bankAccountHolderEmail": "fsdfds@gmail.com",
        "bankAccountHolderName": "fdsfd",
        "bankAccountHolderNickname": "",
        "firstName": "jghjgjgjhj",
        "lastName": "hfghfgh",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "bn",
        "beneficiaryState": "Tutong District",
        "beneficiaryCity": "jghjgjgh",
        "beneficiaryStreet": "200",
        "beneficiaryHouseNumber": "100",
        "beneficiaryZipCode": "",
        "bankFlag": null,
        "currencyISO": {
            "code": "MXN",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/MXN.png",
            "currencyName": null
        },
        "currency": "MXN",
        "paymentReason": 25,
        "reasonDesc": null,
        "bankCountry": "bf",
        "bankName": "BANK OF AFRICA-BURKINA FASO",
        "bankAddress": null,
        "bankNumber": "084",
        "bankBranch": "",
        "iban": "BF42BF0840101300463574000390",
        "swiftCode": "AFRIBFBFXXX",
        "accountNumber": "00463574000390",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-02-05T07:54:14.923",
        "companyName": null,
        "createdAt": "2025-02-05T07:54:08.93",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": "200 100, jghjgjgh, Tutong District ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "3ae433fe-14ad-49a1-8da5-0519c0ac23aa",
        "status": 1,
        "bankAccountHolderEmail": "test1323@yopmail.com",
        "bankAccountHolderName": "fff",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "יחיחייחליחלי",
        "beneficiaryIdNumber": "875878758",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 25,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "בנק אש ישראל בע\"מ",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "7647643763",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-03-25T10:57:43.607",
        "companyName": null,
        "createdAt": "2025-03-25T10:57:43.607",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "1b0f76bd-ef05-4b8e-8f00-0541779937ad",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "900",
        "iban": "IL680039000000000000555",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "555",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-11T16:01:27.397",
        "companyName": null,
        "createdAt": "2025-04-11T16:01:27.397",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "4c2e0dc9-9c89-4cb7-9aa6-0561137dd4ba",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/10.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Leumi Le-Israel B.M",
        "bankAddress": null,
        "bankNumber": "10",
        "bankBranch": "105",
        "iban": "IL190101050000000066666",
        "swiftCode": "LUMIILIT",
        "accountNumber": "66666",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-25T08:48:07.017",
        "companyName": null,
        "createdAt": "2025-04-25T08:48:07.017",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "6af3b552-ec6d-4564-9ffe-08a49926b742",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/31.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "The First International Bank of Israel Ltd",
        "bankAddress": null,
        "bankNumber": "31",
        "bankBranch": "30",
        "iban": "IL050310300000105634654",
        "swiftCode": "FIRBILIT",
        "accountNumber": "105634654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-03-25T11:33:50.93",
        "companyName": null,
        "createdAt": "2025-03-25T11:33:50.93",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "510e03f8-ddf2-468b-bf9e-08da6e946173",
        "status": 1,
        "bankAccountHolderEmail": "testabc@yopmail.com",
        "bankAccountHolderName": "trt",
        "bankAccountHolderNickname": "",
        "firstName": "kakaka",
        "lastName": "fdgfdg ",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "bj",
        "beneficiaryState": "",
        "beneficiaryCity": "yfgh",
        "beneficiaryStreet": "qwe",
        "beneficiaryHouseNumber": "454",
        "beneficiaryZipCode": "3444",
        "bankFlag": null,
        "currencyISO": {
            "code": "AUD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/AUD.png",
            "currencyName": null
        },
        "currency": "AUD",
        "paymentReason": 11,
        "reasonDesc": null,
        "bankCountry": "at",
        "bankName": "RAIFFEISENLANDESBANK NIEDERÖSTERREICH-WIEN AG",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "AT483200000012345864",
        "swiftCode": "RLNWATWWXXX",
        "accountNumber": "00012345864",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "f4ef5927-c161-408f-a55f-f642845ea7b1"
            }
        ],
        "updatedAt": "2025-04-07T12:50:08.53",
        "companyName": null,
        "createdAt": "2025-04-07T12:50:01.34",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "qwe 454, yfgh,  3444",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "0707af53-7be0-4988-ae11-09c8220edef1",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/20.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Mizrahi Tefahot Bank Ltd",
        "bankAddress": null,
        "bankNumber": "20",
        "bankBranch": "917",
        "iban": "IL890209170004353534535",
        "swiftCode": "MIZBILIT",
        "accountNumber": "4353534535",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-07T11:15:49.873",
        "companyName": null,
        "createdAt": "2025-04-07T11:15:49.873",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "b3837702-ba9b-4a99-b407-09dcda4412d1",
        "status": 1,
        "bankAccountHolderEmail": "wabisi2070@botsoko.com",
        "bankAccountHolderName": "test abcm beneficiary",
        "bankAccountHolderNickname": "eurman",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "al",
        "beneficiaryState": "",
        "beneficiaryCity": "Bnei Brak TEST",
        "beneficiaryStreet": "Derech Sheshet HaYam",
        "beneficiaryHouseNumber": "30",
        "beneficiaryZipCode": "5120261",
        "bankFlag": null,
        "currencyISO": {
            "code": "PLN",
            "sign": "zł",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/PLN.png",
            "currencyName": null
        },
        "currency": "PLN",
        "paymentReason": 20,
        "reasonDesc": null,
        "bankCountry": "dz",
        "bankName": "SOCIETE GENERALE ALGERIE",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "DZ580002100001113000000570",
        "swiftCode": "SOGEDZALXXX",
        "accountNumber": "113000000570",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "3ed45619-6198-49c8-aa4d-1cf1a8ff4607"
            },
            {
                "docType": 11,
                "fileId": "6f5cdc81-6e15-4f51-904e-c3014f8f9def"
            },
            {
                "docType": 11,
                "fileId": "7a07b093-d6bc-4fb9-88e4-dc2883c56507"
            },
            {
                "docType": 11,
                "fileId": "099c6ee1-c280-48c2-9481-38fddee2f40c"
            },
            {
                "docType": 11,
                "fileId": "4c6bcc9c-5418-4549-bb34-816f70aa6871"
            },
            {
                "docType": 11,
                "fileId": "61ee442f-8296-44f9-a03e-6593f52e7f0e"
            },
            {
                "docType": 11,
                "fileId": "93c588ff-7481-4827-8bbe-f0353bc1b099"
            },
            {
                "docType": 11,
                "fileId": "94e1d279-cfdc-4f4a-94b5-5118f08e9e12"
            },
            {
                "docType": 11,
                "fileId": "395170a1-dcc2-49fd-8f71-b78806bf9f69"
            },
            {
                "docType": 11,
                "fileId": "0f7a10c2-3aea-4f0a-ae6e-aaf324d28bd1"
            },
            {
                "docType": 11,
                "fileId": "2e613e56-93d2-4024-b7a8-dc57e17edc10"
            },
            {
                "docType": 11,
                "fileId": "aadd28cc-f4f6-4c74-96af-630453d637f3"
            }
        ],
        "updatedAt": "2025-04-29T09:10:54.737",
        "companyName": null,
        "createdAt": "2025-04-29T09:10:47.44",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "Derech Sheshet HaYam 30, Bnei Brak TEST,  5120261",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "0267c731-eb74-4650-895b-0aa534fc2c42",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Esh Israel LTD",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "1",
        "iban": "IL450030010000000000001",
        "swiftCode": "EIETILITXXX",
        "accountNumber": "1",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-25T13:42:56.053",
        "companyName": null,
        "createdAt": "2025-04-25T13:42:56.053",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "63f6a7af-0131-4272-90c5-0b69010e97dd",
        "status": 1,
        "bankAccountHolderEmail": "test@yopmail.com",
        "bankAccountHolderName": "rwererwerw",
        "bankAccountHolderNickname": "tesst",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "il",
        "beneficiaryState": "",
        "beneficiaryCity": "yy",
        "beneficiaryStreet": "wrwrwr",
        "beneficiaryHouseNumber": "23232",
        "beneficiaryZipCode": "3444",
        "bankFlag": null,
        "currencyISO": {
            "code": "USD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/USD.png",
            "currencyName": null
        },
        "currency": "USD",
        "paymentReason": 22,
        "reasonDesc": null,
        "bankCountry": "fr",
        "bankName": "CREDIT AGRICOLE S A",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "FR7630006000011234567890189",
        "swiftCode": "AGRIFRPPXXX",
        "accountNumber": "12345678901",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "f6aa82af-8d54-47d3-b526-d455114526fe"
            }
        ],
        "updatedAt": "2025-04-29T12:12:11.953",
        "companyName": null,
        "createdAt": "2025-04-29T12:12:04.39",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "wrwrwr 23232, yy,  3444",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "08587ad1-072f-46f3-b065-0bab7ddab397",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/4.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Yahav for Government Employees Ltd",
        "bankAddress": null,
        "bankNumber": "4",
        "bankBranch": "119",
        "iban": "IL400041190034534645777",
        "swiftCode": "BYAHILI1",
        "accountNumber": "34534645777",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-07T12:32:23.903",
        "companyName": null,
        "createdAt": "2025-04-07T12:32:23.903",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "306447a5-fe20-4e01-96a1-0c8f9f142830",
        "status": 1,
        "bankAccountHolderEmail": "testabc@yopmail.com",
        "bankAccountHolderName": "bpbp",
        "bankAccountHolderNickname": "",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "ודקר יםךגקר",
        "beneficiaryIdNumber": "362466465",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "",
        "beneficiaryStreet": "",
        "beneficiaryHouseNumber": "",
        "beneficiaryZipCode": "",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/3.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 25,
        "reasonDesc": null,
        "bankCountry": "il",
        "bankName": "בנק אש ישראל בע\"מ",
        "bankAddress": null,
        "bankNumber": "3",
        "bankBranch": "900",
        "iban": "",
        "swiftCode": "",
        "accountNumber": "001234567890",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-03-26T10:34:00.77",
        "companyName": null,
        "createdAt": "2025-03-26T10:33:54.667",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": " , ,  ",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "ae08aeec-dc76-4e8e-aad9-0dcd3396e175",
        "status": 1,
        "bankAccountHolderEmail": "laxopon264@roborena.com",
        "bankAccountHolderName": "Bank account holder name",
        "bankAccountHolderNickname": "eurman",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": "665465446",
        "beneficiaryCountry": "be",
        "beneficiaryState": "",
        "beneficiaryCity": "4566654",
        "beneficiaryStreet": "jhbvghvhb",
        "beneficiaryHouseNumber": "232zaaaaaa@#$%^&***",
        "beneficiaryZipCode": "46546545",
        "bankFlag": null,
        "currencyISO": {
            "code": "GBP",
            "sign": "£",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/GBP.png",
            "currencyName": null
        },
        "currency": "GBP",
        "paymentReason": 1,
        "reasonDesc": null,
        "bankCountry": "be",
        "bankName": "BELFIUS BANK",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "BE71096123456769",
        "swiftCode": "GKCCBEBBXXX",
        "accountNumber": "123456769",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 5,
                "fileId": "e4577ad5-c072-4489-83ce-cef3e4816e20"
            },
            {
                "docType": 6,
                "fileId": "baad60f3-cdd8-4f64-a73a-d5983c1b11d0"
            }
        ],
        "updatedAt": "2025-04-14T14:08:15.91",
        "companyName": null,
        "createdAt": "2025-01-28T07:01:03.607",
        "deductionNum": "464654",
        "beneficiaryStateResidenceRecipient": "ad",
        "aba": "",
        "beneficiaryAddress": "jhbvghvhb 232zaaaaaa@#$%^&***, 4566654,  46546545",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "81b6c713-6001-49c9-a18c-0df326c34caf",
        "status": 1,
        "bankAccountHolderEmail": "f@gmail.com",
        "bankAccountHolderName": "fdsfsdfd",
        "bankAccountHolderNickname": "hgfh",
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": "454564656",
        "beneficiaryCountry": "us",
        "beneficiaryState": "Arizona",
        "beneficiaryCity": "Anthem",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": "1000",
        "beneficiaryZipCode": "45645656",
        "bankFlag": null,
        "currencyISO": {
            "code": "USD",
            "sign": "$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/USD.png",
            "currencyName": null
        },
        "currency": "USD",
        "paymentReason": 2,
        "reasonDesc": null,
        "bankCountry": "us",
        "bankName": "U.S. BANK N.A.",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "",
        "swiftCode": "USBKUS44XXX",
        "accountNumber": "113000000570",
        "bankAccountType": 2,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 5,
                "fileId": "5e8a5f57-4ab9-4c29-b052-9bd618c18557"
            }
        ],
        "updatedAt": "2025-03-05T10:39:11.423",
        "companyName": null,
        "createdAt": "2025-03-05T10:39:04.29",
        "deductionNum": "46465456",
        "beneficiaryStateResidenceRecipient": "us",
        "aba": "543534253",
        "beneficiaryAddress": " 1000, Anthem, Arizona 45645656",
        "routingCodeType": 6,
        "routingCodeValue": "543534253",
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "bb079c3d-1b4f-49a2-899e-0e925a90453e",
        "status": 2,
        "bankAccountHolderEmail": "bapojo9783@polatrix.com",
        "bankAccountHolderName": "kokol",
        "bankAccountHolderNickname": null,
        "firstName": null,
        "lastName": null,
        "bankAccountHolderHebrewName": null,
        "beneficiaryIdNumber": "333110328",
        "beneficiaryCountry": "il",
        "beneficiaryState": null,
        "beneficiaryCity": "tel aviv",
        "beneficiaryStreet": null,
        "beneficiaryHouseNumber": null,
        "beneficiaryZipCode": "5555",
        "bankFlag": "https://okoora-stage-api2023.azurewebsites.net/Images/BanksFlags/4.svg",
        "currencyISO": {
            "code": "ILS",
            "sign": "₪",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/ILS.png",
            "currencyName": null
        },
        "currency": "ILS",
        "paymentReason": 18,
        "reasonDesc": null,
        "bankCountry": "IL",
        "bankName": "Bank Yahav for Government Employees Ltd",
        "bankAddress": null,
        "bankNumber": "4",
        "bankBranch": "245",
        "iban": "IL550042450000000123654",
        "swiftCode": "BYAHILI1",
        "accountNumber": "123654",
        "bankAccountType": 3,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": 1,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-07T12:26:05.463",
        "companyName": null,
        "createdAt": "2025-04-07T12:26:05.463",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": null,
        "beneficiaryAddress": "tel aviv,  5555",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "7cd3364b-659b-470f-babe-0eb076ed2c06",
        "status": 1,
        "bankAccountHolderEmail": "test@yopmail.com",
        "bankAccountHolderName": "Ebenezer Emergency Fund International",
        "bankAccountHolderNickname": "test",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "dz",
        "beneficiaryState": "",
        "beneficiaryCity": "Algiers",
        "beneficiaryStreet": "hh==gsds",
        "beneficiaryHouseNumber": "6536543654",
        "beneficiaryZipCode": "3444",
        "bankFlag": null,
        "currencyISO": {
            "code": "CHF",
            "sign": "CHF",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/CHF.png",
            "currencyName": null
        },
        "currency": "CHF",
        "paymentReason": 11,
        "reasonDesc": null,
        "bankCountry": "gb",
        "bankName": "LLOYDS BANK PLC",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "GB81LOYD30910811344978",
        "swiftCode": "LOYDGB2LXXX",
        "accountNumber": "11344978",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "e40d8fe7-9823-4e26-aaa6-401264e90fe7"
            }
        ],
        "updatedAt": "2025-04-29T09:26:42.827",
        "companyName": null,
        "createdAt": "2025-04-17T15:28:42.917",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "hh==gsds 6536543654, Algiers,  3444",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
    {
        "id": "f8443730-c40e-4d95-a342-0f2bda80c685",
        "status": 5,
        "bankAccountHolderEmail": "test@gmail.com",
        "bankAccountHolderName": "e5iee",
        "bankAccountHolderNickname": "dykykdydu",
        "firstName": "",
        "lastName": "",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "ar",
        "beneficiaryState": "",
        "beneficiaryCity": "rudduf",
        "beneficiaryStreet": "dyodydd",
        "beneficiaryHouseNumber": "574774",
        "beneficiaryZipCode": "37747",
        "bankFlag": null,
        "currencyISO": {
            "code": "CAD",
            "sign": "C$",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/CAD.png",
            "currencyName": null
        },
        "currency": "CAD",
        "paymentReason": 1,
        "reasonDesc": null,
        "bankCountry": "be",
        "bankName": "RAIFFEISENLANDESBANK NIEDEROESTERREICH-WIEN AG",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "AT483200000012345864",
        "swiftCode": "RLNWATWWXXX",
        "accountNumber": "00012345864",
        "bankAccountType": 1,
        "beneficiaryAccountType": 1,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [],
        "updatedAt": "2025-04-14T13:36:33.457",
        "companyName": null,
        "createdAt": "2025-04-14T13:36:33.457",
        "deductionNum": null,
        "beneficiaryStateResidenceRecipient": null,
        "aba": "",
        "beneficiaryAddress": "dyodydd 574774, rudduf,  37747",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": false,
        "relatedPayments": false
    },
    {
        "id": "367c7c0a-99d6-4a52-8ce7-0fafdc268caf",
        "status": 1,
        "bankAccountHolderEmail": "devbusi@yopmail.com",
        "bankAccountHolderName": "egrtt",
        "bankAccountHolderNickname": "",
        "firstName": "fsdfsfs",
        "lastName": "dfsfsdf",
        "bankAccountHolderHebrewName": "",
        "beneficiaryIdNumber": null,
        "beneficiaryCountry": "al",
        "beneficiaryState": "",
        "beneficiaryCity": "uyfd",
        "beneficiaryStreet": "7 Imbar st",
        "beneficiaryHouseNumber": "6536543654",
        "beneficiaryZipCode": "3444",
        "bankFlag": null,
        "currencyISO": {
            "code": "CHF",
            "sign": "CHF",
            "flag": "https://okoora-stage-api2023.azurewebsites.net/Images/Flags/CHF.png",
            "currencyName": null
        },
        "currency": "CHF",
        "paymentReason": 11,
        "reasonDesc": null,
        "bankCountry": "de",
        "bankName": "Societe Generale",
        "bankAddress": null,
        "bankNumber": "",
        "bankBranch": "",
        "iban": "DE75512108001245126199",
        "swiftCode": "SOGEDEFFXXX",
        "accountNumber": "1245126199",
        "bankAccountType": 1,
        "beneficiaryAccountType": 2,
        "paymentTerms": null,
        "ownAccount": null,
        "beneficiaryFiles": [
            {
                "docType": 1,
                "fileId": "ac905f81-63a0-4db0-b028-fd9c6a7d3731"
            }
        ],
        "updatedAt": "2025-04-07T13:23:28.597",
        "companyName": null,
        "createdAt": "2025-04-07T13:23:20.287",
        "deductionNum": "",
        "beneficiaryStateResidenceRecipient": "",
        "aba": "",
        "beneficiaryAddress": "7 Imbar st 6536543654, uyfd,  3444",
        "routingCodeType": null,
        "routingCodeValue": null,
        "erpBeneficiaryId": null,
        "erpService": null,
        "isBeneficiaryBusinessCategoryLegit": true,
        "relatedPayments": false
    },
]