export const hedgeDealTable =
[
    {
        "mainHedgeDealDto": {
            "id": 7656,
            "tradeDate": "2025-09-15T15:31:57.867",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 197.1,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161913
        },
        "hedgeDeals": [
            {
                "id": 92916,
                "tradeDate": "2025-09-15T15:31:57.867",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 197.1,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161913
            },
            {
                "id": 92917,
                "tradeDate": "2025-09-15T15:31:57.867",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 197.1,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161913
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7655,
            "tradeDate": "2025-09-15T15:31:57.78",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 122.88,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161912
        },
        "hedgeDeals": [
            {
                "id": 92914,
                "tradeDate": "2025-09-15T15:31:57.78",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 122.88,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161912
            },
            {
                "id": 92915,
                "tradeDate": "2025-09-15T15:31:57.78",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 122.88,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161912
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7652,
            "tradeDate": "2025-09-15T15:31:57.58",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 484.79,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161909
        },
        "hedgeDeals": [
            {
                "id": 92908,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 484.79,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161909
            },
            {
                "id": 92909,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 484.79,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161909
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7653,
            "tradeDate": "2025-09-15T15:31:57.58",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 570.46,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161910
        },
        "hedgeDeals": [
            {
                "id": 92910,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 570.46,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161910
            },
            {
                "id": 92911,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 570.46,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161910
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7654,
            "tradeDate": "2025-09-15T15:31:57.58",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 784.71,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161911
        },
        "hedgeDeals": [
            {
                "id": 92912,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 784.71,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161911
            },
            {
                "id": 92913,
                "tradeDate": "2025-09-15T15:31:57.58",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 784.71,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161911
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7651,
            "tradeDate": "2025-09-15T15:31:57.577",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 741.92,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161908
        },
        "hedgeDeals": [
            {
                "id": 92906,
                "tradeDate": "2025-09-15T15:31:57.577",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 741.92,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161908
            },
            {
                "id": 92907,
                "tradeDate": "2025-09-15T15:31:57.577",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 741.92,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161908
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7650,
            "tradeDate": "2025-09-15T15:31:57.437",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 793.87,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161907
        },
        "hedgeDeals": [
            {
                "id": 92904,
                "tradeDate": "2025-09-15T15:31:57.437",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 793.87,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161907
            },
            {
                "id": 92905,
                "tradeDate": "2025-09-15T15:31:57.437",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 793.87,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161907
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7648,
            "tradeDate": "2025-09-15T15:31:57.433",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 605.15,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161905
        },
        "hedgeDeals": [
            {
                "id": 92900,
                "tradeDate": "2025-09-15T15:31:57.433",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 605.15,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161905
            },
            {
                "id": 92901,
                "tradeDate": "2025-09-15T15:31:57.433",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 605.15,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161905
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7649,
            "tradeDate": "2025-09-15T15:31:57.433",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 544.42,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161906
        },
        "hedgeDeals": [
            {
                "id": 92902,
                "tradeDate": "2025-09-15T15:31:57.433",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 544.42,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161906
            },
            {
                "id": 92903,
                "tradeDate": "2025-09-15T15:31:57.433",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 544.42,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161906
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7647,
            "tradeDate": "2025-09-15T15:31:57.417",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 207.63,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161904
        },
        "hedgeDeals": [
            {
                "id": 92898,
                "tradeDate": "2025-09-15T15:31:57.417",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 207.63,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161904
            },
            {
                "id": 92899,
                "tradeDate": "2025-09-15T15:31:57.417",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 207.63,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161904
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7646,
            "tradeDate": "2025-09-15T15:31:57.17",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 524.99,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161903
        },
        "hedgeDeals": [
            {
                "id": 92896,
                "tradeDate": "2025-09-15T15:31:57.17",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 524.99,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161903
            },
            {
                "id": 92897,
                "tradeDate": "2025-09-15T15:31:57.17",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 524.99,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161903
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7645,
            "tradeDate": "2025-09-15T15:31:56.783",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 898.49,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161902
        },
        "hedgeDeals": [
            {
                "id": 92894,
                "tradeDate": "2025-09-15T15:31:56.783",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 898.49,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161902
            },
            {
                "id": 92895,
                "tradeDate": "2025-09-15T15:31:56.783",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 898.49,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161902
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7644,
            "tradeDate": "2025-09-15T15:31:56.513",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 673.8,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161901
        },
        "hedgeDeals": [
            {
                "id": 92892,
                "tradeDate": "2025-09-15T15:31:56.513",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 673.8,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161901
            },
            {
                "id": 92893,
                "tradeDate": "2025-09-15T15:31:56.513",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 673.8,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161901
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7643,
            "tradeDate": "2025-09-15T15:31:56.493",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 756.65,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161900
        },
        "hedgeDeals": [
            {
                "id": 92890,
                "tradeDate": "2025-09-15T15:31:56.493",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 756.65,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161900
            },
            {
                "id": 92891,
                "tradeDate": "2025-09-15T15:31:56.493",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 756.65,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161900
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7641,
            "tradeDate": "2025-09-15T15:31:56.477",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 660.97,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161898
        },
        "hedgeDeals": [
            {
                "id": 92886,
                "tradeDate": "2025-09-15T15:31:56.477",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 660.97,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161898
            },
            {
                "id": 92887,
                "tradeDate": "2025-09-15T15:31:56.477",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 660.97,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161898
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7642,
            "tradeDate": "2025-09-15T15:31:56.473",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 379.88,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161899
        },
        "hedgeDeals": [
            {
                "id": 92888,
                "tradeDate": "2025-09-15T15:31:56.473",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 379.88,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161899
            },
            {
                "id": 92889,
                "tradeDate": "2025-09-15T15:31:56.473",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 379.88,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161899
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7640,
            "tradeDate": "2025-09-15T15:31:56.46",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 157.2,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161897
        },
        "hedgeDeals": [
            {
                "id": 92884,
                "tradeDate": "2025-09-15T15:31:56.46",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 157.2,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161897
            },
            {
                "id": 92885,
                "tradeDate": "2025-09-15T15:31:56.46",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 157.2,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161897
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7639,
            "tradeDate": "2025-09-15T15:31:56.42",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 397.81,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161896
        },
        "hedgeDeals": [
            {
                "id": 92882,
                "tradeDate": "2025-09-15T15:31:56.42",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 397.81,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161896
            },
            {
                "id": 92883,
                "tradeDate": "2025-09-15T15:31:56.42",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 397.81,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161896
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7638,
            "tradeDate": "2025-09-15T15:31:56.377",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 794.14,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161895
        },
        "hedgeDeals": [
            {
                "id": 92880,
                "tradeDate": "2025-09-15T15:31:56.377",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 794.14,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161895
            },
            {
                "id": 92881,
                "tradeDate": "2025-09-15T15:31:56.377",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 794.14,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161895
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7637,
            "tradeDate": "2025-09-15T15:31:56.373",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 204.28,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161894
        },
        "hedgeDeals": [
            {
                "id": 92878,
                "tradeDate": "2025-09-15T15:31:56.373",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 204.28,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161894
            },
            {
                "id": 92879,
                "tradeDate": "2025-09-15T15:31:56.373",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 204.28,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161894
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7636,
            "tradeDate": "2025-09-15T15:31:56.313",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 422.62,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161893
        },
        "hedgeDeals": [
            {
                "id": 92876,
                "tradeDate": "2025-09-15T15:31:56.313",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 422.62,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161893
            },
            {
                "id": 92877,
                "tradeDate": "2025-09-15T15:31:56.313",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 422.62,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161893
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7635,
            "tradeDate": "2025-09-15T15:31:56.18",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 392.66,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161892
        },
        "hedgeDeals": [
            {
                "id": 92874,
                "tradeDate": "2025-09-15T15:31:56.18",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 392.66,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161892
            },
            {
                "id": 92875,
                "tradeDate": "2025-09-15T15:31:56.18",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 392.66,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161892
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7634,
            "tradeDate": "2025-09-15T15:31:56.063",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 876.79,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161891
        },
        "hedgeDeals": [
            {
                "id": 92872,
                "tradeDate": "2025-09-15T15:31:56.063",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 876.79,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161891
            },
            {
                "id": 92873,
                "tradeDate": "2025-09-15T15:31:56.063",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 876.79,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161891
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7633,
            "tradeDate": "2025-09-15T15:31:56.023",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 166.64,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161890
        },
        "hedgeDeals": [
            {
                "id": 92870,
                "tradeDate": "2025-09-15T15:31:56.023",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 166.64,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161890
            },
            {
                "id": 92871,
                "tradeDate": "2025-09-15T15:31:56.023",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 166.64,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161890
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7632,
            "tradeDate": "2025-09-15T15:31:55.803",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 756.11,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161889
        },
        "hedgeDeals": [
            {
                "id": 92868,
                "tradeDate": "2025-09-15T15:31:55.803",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 756.11,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161889
            },
            {
                "id": 92869,
                "tradeDate": "2025-09-15T15:31:55.803",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 756.11,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161889
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7631,
            "tradeDate": "2025-09-15T15:31:55.657",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 278.84,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161888
        },
        "hedgeDeals": [
            {
                "id": 92866,
                "tradeDate": "2025-09-15T15:31:55.657",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 278.84,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161888
            },
            {
                "id": 92867,
                "tradeDate": "2025-09-15T15:31:55.657",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 278.84,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161888
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7630,
            "tradeDate": "2025-09-15T15:31:55.653",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 104.97,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161887
        },
        "hedgeDeals": [
            {
                "id": 92864,
                "tradeDate": "2025-09-15T15:31:55.653",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 104.97,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161887
            },
            {
                "id": 92865,
                "tradeDate": "2025-09-15T15:31:55.653",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 104.97,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161887
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7628,
            "tradeDate": "2025-09-15T15:31:55.63",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 167.1,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161885
        },
        "hedgeDeals": [
            {
                "id": 92860,
                "tradeDate": "2025-09-15T15:31:55.63",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 167.1,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161885
            },
            {
                "id": 92861,
                "tradeDate": "2025-09-15T15:31:55.63",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 167.1,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161885
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7629,
            "tradeDate": "2025-09-15T15:31:55.63",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 736.17,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161886
        },
        "hedgeDeals": [
            {
                "id": 92862,
                "tradeDate": "2025-09-15T15:31:55.63",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 736.17,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161886
            },
            {
                "id": 92863,
                "tradeDate": "2025-09-15T15:31:55.63",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 736.17,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161886
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7627,
            "tradeDate": "2025-09-15T15:31:55.62",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 821.98,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161884
        },
        "hedgeDeals": [
            {
                "id": 92858,
                "tradeDate": "2025-09-15T15:31:55.62",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 821.98,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161884
            },
            {
                "id": 92859,
                "tradeDate": "2025-09-15T15:31:55.62",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 821.98,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161884
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7626,
            "tradeDate": "2025-09-15T15:31:55.587",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 795.02,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161883
        },
        "hedgeDeals": [
            {
                "id": 92856,
                "tradeDate": "2025-09-15T15:31:55.587",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 795.02,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161883
            },
            {
                "id": 92857,
                "tradeDate": "2025-09-15T15:31:55.587",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 795.02,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161883
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7625,
            "tradeDate": "2025-09-15T15:31:55.573",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 226.83,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161882
        },
        "hedgeDeals": [
            {
                "id": 92854,
                "tradeDate": "2025-09-15T15:31:55.573",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 226.83,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161882
            },
            {
                "id": 92855,
                "tradeDate": "2025-09-15T15:31:55.573",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 226.83,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161882
            }
        ]
    },
    {
        "mainHedgeDealDto": {
            "id": 7624,
            "tradeDate": "2025-09-15T15:31:55.547",
            "dealType": 1,
            "pair": "AUDILS",
            "strike": 2.21214046,
            "amount": 833.92,
            "currencySign": "$",
            "isOnline": true,
            "expiryDate": "2025-09-29T00:00:00",
            "isOpen": true,
            "isProfit": false,
            "canCloseDeal": true,
            "callPutType": 0,
            "fairValue": null,
            "dealStatus": 2,
            "strategyId": 161881
        },
        "hedgeDeals": [
            {
                "id": 92852,
                "tradeDate": "2025-09-15T15:31:55.547",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 833.92,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 0,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161881
            },
            {
                "id": 92853,
                "tradeDate": "2025-09-15T15:31:55.547",
                "dealType": 1,
                "pair": "AUDILS",
                "strike": 2.21214046,
                "amount": 833.92,
                "currencySign": "$",
                "isOnline": true,
                "expiryDate": "2025-09-29T00:00:00",
                "isOpen": true,
                "isProfit": null,
                "canCloseDeal": true,
                "callPutType": 1,
                "fairValue": null,
                "dealStatus": 2,
                "strategyId": 161881
            }
        ]
    }
]